### ISSUE TITLE
Error about missing values

### ISSUE THREAD

**Issue by AnnaManasyan** [riccardo-df/valiCATE#3]
I am running the following code from evaluCATE package and I get an error about missing values.
However  at_msamean ,W, X, cf_at_msamean, index_vector have no NaN values.
at_msamean - outcome
W - treatment
X - covariates
cf_at_msamean - causal forest predictions 
index_vector - train indices 

evaluation <- evaluCATE(at_msamean ,W, X, cf_at_msamean, index_vector,  verbose = FALSE)

Error in quantile.default(x, cutoffs) : missing values and NaN's not allowed if 'na.rm' is FALSE

**Comment by riccardo-df** [comment]
Thanks for raising the issue. It would help to see your data (or synthetic data if yours cannot be shared) and a script reproducing the error. Is this possible?

**Comment by AnnaManasyan** [comment]
Thank you for replying! 
You can find the data here https://www.openicpsr.org/openicpsr/project/113783/version/V1/view?path=/openicpsr/113783/fcr:versions/V1&type=project

This script should reproduce the results.

`data <- read_dta(data_path_here)
data  <- subset(data, T3 == 1)
data <- na.omit(data)

data <- dummy_cols(data, 
                   select_columns = c('s_estcivil', 's_estrato', 's_teneviv'))

X = model.matrix(~ 0 + s_estcivil_1 +s_estcivil_5 + s_num18 + s_utilities + survey_selected  + s_sexo + s_yrs + s_infraest_hh + s_over_age + s_estrato_0 + s_estrato_1 + s_estrato_2 + s_yrshead + s_durables  + s_years_back + s_teneviv_1+s_teneviv_2+s_teneviv_3+s_teneviv_4 + s_single + s_age_sorteo  +  s_tpersona + grade, data = data)

W = model.matrix(~ 0 + T3_treat, data = data)

at_msamean = model.matrix(~ 0 + at_msamean, data = data)

train_proportion <- 0.8
test_proportion <- 1 - train_proportion
train_indices <- sample(seq_len(nrow(data)), size = floor(train_proportion * nrow(data)))

X_train = X[train_indices,]
X_test = X[-train_indices,]

W_train = W[train_indices]
W_test = W[-train_indices]

at_msamean_train = at_msamean[train_indices]
at_msamean_test = at_msamean[-train_indices]

CF_at_msamean = causal_forest(X_train,at_msamean_train,W_train)
cf_at_msamean = predict(CF_at_msamean,X_test)$predictions

index_vector <- rep(FALSE, nrow(X))
index_vector[train_indices] <- TRUE

evaluation <- evaluCATE(at_msamean ,W, X, cf_at_msamean, index_vector,  verbose = FALSE)
`

**Comment by riccardo-df** [comment]
I think I can solve your issue without the data (which I am having trouble accessing - maybe you can share the output of the `dput` function called on your data?). 

The `evaluCATE` function requires us to pass the CATE predictions on the full sample, that is, `X`. Can you try replacing this line:

```cf_at_msamean = predict(CF_at_msamean,X_test)$predictions```

with:

```cf_at_msamean = predict(CF_at_msamean,X)$predictions```

I hope this fixes your issue.

**Comment by AnnaManasyan** [comment]
Dear Riccardo,
It worked! Thanks.

**Comment by riccardo-df** [comment]
Thank you, Anna!

I updated the documentation of the `evaluCATE` function - I hope it will be easier for future users to avoid this issue.
