### ISSUE TITLE
Error: system is exactly singular

### ISSUE THREAD

**Issue by jzhenli1** [riccardo-df/valiCATE#4]
I am running the main function from the evaluCATE package but I receive the following error messages:
`Error in solve.default(vcov.hyp) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0`
AND
`Error: We have one or more homogeneous groups. Please try a different 'k' or a different sample split.`

The error message depends on which meta-learner I use.

Thank you in advance for your help!

Here is my code snippet:

# Calculate true propensity score
`propensity_model <- glm(W ~ X, family = binomial())`
`propensity_score <- predict(propensity_model, type = "response")`

# Derive logical vector train_idx
`train_idx <- rep(FALSE, length(Y))`
`train_idx[indices] <- TRUE`

# Full sample prediction
`cate_tl_eval <- predict(rfm1, X)$predictions - predict(rfm0, X)$predictions`
`cate_cf_eval <- predict(cf, X)$predictions`
`cate_rl_eval <- predict(rf_rl, X)$predictions`
`cate_drl_eval <- predict(rf_drl, X)$predictions`

## Call main function.
`evaluation <- evaluCATE(Y, W, X, cate_tl_eval, train_idx, pscore = propensity_score, verbose = FALSE)`
`Error in solve.default(vcov.hyp) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0`

`evaluation <- evaluCATE(Y, W, X, cate_cf_eval, train_idx, pscore = propensity_score, verbose = FALSE)`
`Error in solve.default(vcov.hyp) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0`

`evaluation <- evaluCATE(Y, W, X, cate_rl_eval, train_idx, pscore = propensity_score, verbose = FALSE)`
`Error: We have one or more homogeneous groups. Please try a different 'k' or a different sample split.`

`evaluation <- evaluCATE(Y, W, X, cate_drl_eval, train_idx, pscore = propensity_score, verbose = FALSE)`
`Error: We have one or more homogeneous groups. Please try a different 'k' or a different sample split.`

**Comment by riccardo-df** [comment]
Thanks for raising the issue.

I would need the whole script and data to reproduce your first error. Can you provide them?

About the second error: `We have one or more homogeneous groups. Please try a different 'k' or a different sample split.` 
- This is raised by the function performing the GATES estimation and means that at least one of the generated groups has only treated or only control units. An error is raised as this would lead to multicollinearity issues in some of our estimation strategies.
- Groups are generated by cutting the distribution of the estimated CATEs. This is why the error depends on the CATE estimator you use.
- One way out is to try a different training-test sample split. Another solution is to try a different number of groups, as controlled by the parameter `n_groups` (`k` was the original name of this parameter - apparently, I forgot to adjust the text displayed by the error; I will fix this immediately).

**Comment by jzhenli1** [comment]
Thank you for your help!
You can download the data here: https://data.mendeley.com/datasets/jb9734nrp7/1

## Data Restructuring
```
set.seed(1234)

# Importing data
data <- read_dta("Data/replication_data_village_incident.dta")

# Create treatment time indicator variable pre vs. post treatment
data <- data %>% 
  mutate(pretreat = (year <= 2008) | (year == 2009 & month <= 3))

# Reordering columns
data <- data %>%
  select(pretreat, everything())

# Create dataframe with post-treatment outcomes
postOutcome <- data %>%
  filter(!pretreat) %>%
  select(treat, incidents)

# Create dataframe with pre-treatment covariates starting 2007 July
# (in order to keep the number of observations same for pretreat covariates and post-treat outcome)
preCovar <- data %>%
  filter(pretreat) %>% 
  filter(year > 2007 | (year == 2007 & month >= 7)) %>% 
  select(-pretreat, -treat, -year, -month, -incidents, -(16:23))

# Column bind the 2 dataframes
df <- cbind(postOutcome, preCovar)

# Creating high baseline conflict indicator
df <- df %>% 
  mutate(highconflict = if_else(!municipality %in% c('Lala', 'Jimalalud', 'Basay'), 1, 0)) %>% 
  select(treat, incidents, highconflict, everything()) 
```

## Creating Pseudo-Outcome
```
# Outcome
Y <- df$incidents
# Treatment
W <- df$treat
# Create main effects matrix
X <- model.matrix(~ 0 + highconflict + pop00 + streetpattern + power + 
                    comm_waterworks + hospital + clinic + acc_natl_hwy, data = df)

# 3-fold cross-fitting with causalDML package (while tuning the forest)
forest <- create_method("forest_grf", args = list(tune.parameters = "all"))
aipw <- DML_aipw(Y, W, X,
                 ml_w = list(forest),
                 ml_y = list(forest),
                 cf = 3)
aipw <- DML_aipw(Y, W, X)
summary(aipw$ATE)
```

## Learners
```
# Sample splitting
# Generate a random vector of indices
indices <- sample(1:nrow(X), size = 0.7*nrow(X))

# Split the data
X_train <- X[indices,]
X_test <- X[-indices,]
W_train <- W[indices]
W_test <- W[-indices]
Y_train <- Y[indices]
Y_test <- Y[-indices]

# T-learner
rfm1 <- regression_forest(X_train[W_train == 1,], Y_train[W_train == 1])
rfm0 <- regression_forest(X_train[W_train == 0,], Y_train[W_train == 0])
cate_tl <- predict(rfm1, X_test)$predictions - predict(rfm0, X_test)$predictions

# Causal Forest
cf <- causal_forest(X_train, Y_train, W_train)
cate_cf <- predict(cf, X_test)$predictions

# R-Learner
# Extracting nuisance parameters from causal forest
mhat <- cf$Y.hat
ehat <- cf$W.hat
# Create residuals
res_y <- Y_train - mhat
res_w <- W_train - ehat
# Create pseudo-outcome (outcome res divided by treatment res)
pseudo_rl <- res_y / res_w
# Create weights
weights_rl <- res_w^2
# Weighted regression with random forest
# Fitting reg forest on training sample
rf_rl <- regression_forest(X_train, pseudo_rl, sample.weights = weights_rl)
# Predicting CATE on test sample
cate_rl <- predict(rf_rl, X_test)$predictions

# DR-Learner
# Creating pseudo-outcome for training sample
Y_tilde <- aipw$ATE$delta[indices]
# Fitting reg forest on training sample
rf_drl <- regression_forest(X_train, Y_tilde)
# Predicting CATE in test sample
cate_drl <- predict(rf_drl, X_test)$predictions
```

## evaluCATE
```
# Calculate true propensity score
propensity_model <- glm(W ~ X, family = binomial())
propensity_score <- predict(propensity_model, type = "response")

# Derive logical vector train_idx
train_idx <- rep(FALSE, length(Y))
train_idx[indices] <- TRUE

# Full sample prediction
cate_tl_eval <- predict(rfm1, X)$predictions - predict(rfm0, X)$predictions
cate_cf_eval <- predict(cf, X)$predictions
cate_rl_eval <- predict(rf_rl, X)$predictions
cate_drl_eval <- predict(rf_drl, X)$predictions

## Call main function
evaluation_tl <- evaluCATE(Y, W, X, cate_tl_eval, train_idx, pscore = propensity_score, verbose = FALSE)
Error in solve.default(vcov.hyp) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0

evaluation_cf <- evaluCATE(Y, W, X, cate_cf_eval, train_idx, pscore = propensity_score, verbose = FALSE)
Error in solve.default(vcov.hyp) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0

evaluation_rl <- evaluCATE(Y, W, X, cate_rl_eval, train_idx, pscore = propensity_score, verbose = FALSE)
Error: We have one or more homogeneous groups. Please try a different 'k' or a different sample split.

evaluation_drl <- evaluCATE(Y, W, X, cate_drl_eval, train_idx, pscore = propensity_score, verbose = FALSE)
Error: We have one or more homogeneous groups. Please try a different 'k' or a different sample split.
```

**Comment by riccardo-df** [comment]
I think I identified where the issue comes from, but I have not a direct solution (although I found a way out).

Apparently, you have an outcome with quite a low variation. Running `table(Y)` returns:

```
Y
   0    1    2 
2710   19    1 
```

During the GATES estimation, having so many zeroes leads to some groups featuring a constant outcome (in particular, groups 2, 3, and 5 here), and this causes the `lm_robust` function to return null coefficients and standard deviations for those groups. The error is then raised by the `linearHypothesis` function.

One way out is to increase the fraction of observations allocated to the test sample, thus reducing the risk of this event happening. I changed the following line from your code to allocate only 30% of observations to the training sample:

```
indices <- sample(1:nrow(X), size = 0.3*nrow(X)) # Original was 0.7*nrow(X)
```
 
This solves the first error you received.

Going back to the other error, I fixed that by setting `n_groups = 4` in the last two calls you make to the `evaluCATE` function (those for the R- and DR-learner), although I would suggest you change the value of this parameter to the other calls as well to have comparable results.

Let me also discuss another potential concern in your code. To achieve valid inference, we must estimate the CATEs using only the training data, and process the out-of-sample predictions using only the test data. If I read your code correctly, you obtain estimates of the AIPW pseudo-outcomes using the whole sample and then use a subset of these to estimate the CATEs in a DR-fashion. I attach the relevant lines with some comments:

```
aipw <- DML_aipw(Y, W, X) # Estimated using the whole sample.
Y_tilde <- aipw$ATE$delta[indices] # Take a subset, but still estimated using the whole sample.
rf_drl <- regression_forest(X_train, Y_tilde) # In a way, the outcome here depends on the whole sample.
cate_drl <- predict(rf_drl, X_test)$predictions
```

I would need to think more about this, but this could be a concern for inference. Maybe you should estimate the pseudo-outcomes using only the training data. Or maybe I am just too tired and my brain stopped braining. 

Anyway, I will leave this issue open in case you get other errors I missed with this code. Please let me know if you are able to run the code successfully.

**Comment by jzhenli1** [comment]
Thank you so much for this detailed explanation.
Reducing the training sample size from 70% to 30% did indeed solve the problem!

Regarding the inference concern, I think you are correct. For the DR-Learner, I will re-run the aipw only on the training sample and proceed with out-of-sample predictions. (We were asked to estimate ATE of the full sample for the beginning of the assignment)

**Comment by riccardo-df** [comment]
Awesome. Good luck with your assignment!
